### ISSUE TITLE
Better example of what this / how it works

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/sitedown#21]
This module is super underrated, and I think its because it could be described better.  I have ideas but don't have time to describe them right now. Just stubbing out this issue for now.

**Comment by ungoldman** [comment]
:+1:

**Comment by Flet** [comment]
Hmm, I bet this could work well to replace my ad-hoc site generation on `feross/standard-www`

**Comment by bcomnes** [comment]
I was thinking that could be step 2 after I get ferros to switch over to netlify.  I need to ping him someday and we can coordinate that.

**Comment by bcomnes** [comment]
Good enough for now
