### ISSUE TITLE
Use marky-markdown?

### ISSUE THREAD

**Issue by Flet** [hypermodules/sitedown#22]
Has `marky-markdown` been considered instead of using `markdown-it` directly?

>`marky-markdown` is a markdown parser, written in NodeJS, that aims for 
parity with [GitHub-style markdown]. It is built on top of [`markdown-it`],
a [CommonMark] markdown parser. You can use marky-markdown: 
>
>- [programmatically in NodeJS]
>- [in your terminal]
>- [in the browser] *does not yet support syntax highlighting
>
>`marky-markdown` is the thing that parses package READMEs on 
http://www.npmjs.com.

https://www.npmjs.com/package/marky-markdown

Having parity to the way GitHub parses markdown would be a nice convention to rely on.

I started playing with switching over to `marky-markdown` locally and it worked, but then I realized my fork of `sitedown` was very, very old :/

One drawback: `marky-markdown` uses `highlights` for syntax highlighting, which requires `oniguruma`, which needs to be built at install via node-gyp. I can totally see how this could be a deal breaker for this project.

One thing that is holding back using `sitedown` with `standard-www` is generating anchors for headings automatically, which `marky-markdown` does out of the box. It certainly could be built for `sitedown` separately too...

**Comment by bcomnes** [comment]
I'm not sure?  Sure would be nice to avoid native deps though.  I know markdown-it has plugins, and I'm sure there are plugins fore the anchors.  

Does markdown-it have issues with conforming to common mark ?

**Comment by ungoldman** [comment]
@Flet I'm not against it -- I've investigated trying to use it. It's what npm uses under the hood. I've noticed some parsing issues on npm's site with several readmes though, so I'm not sure it achieves the parity it aims for.

It depends on `markdown-it` as well (same thing as sitedown), so most likely we could either try using it wholesale and ensuring it renders everything correctly, or trying to pull in the plugins marky uses that we currently lack.

I use https://ungoldman.github.io/style.css/guide.html locally to ensure everything renders correctly -- might be a good idea to pull that in markdown in as a test page for sitedown.

**Comment by ungoldman** [comment]
@Flet see https://github.com/npm/npm/pull/15630 :)

**Comment by bcomnes** [comment]
The real problem is that github needs to add the definition lists plugin.

**Comment by ungoldman** [comment]
I threw in a bunch of plugins for sitedown -- https://github.com/hypermodules/sitedown/issues/11

**Comment by ungoldman** [comment]
Source for style guide markdown test page https://raw.githubusercontent.com/ungoldman/style.css/master/guide.md

**Comment by ungoldman** [comment]
Just learned github is migrating towards common mark (mostly)

- https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown
- https://githubengineering.com/a-formal-spec-for-github-markdown/
- https://github.github.com/gfm/

**Comment by ungoldman** [comment]
markdown-it follows the common mark spec as well -- there's an heading anchor plugin but marky markdown doesn't seem to use it https://www.npmjs.com/package/markdown-it-anchor

**Comment by ungoldman** [comment]
yep, 'twas a DIY job https://github.com/npm/marky-markdown/blob/master/lib/plugin/heading-links.js

**Comment by Flet** [comment]
Yeah, the way GitHub calculates the anchor IDs was a bit different than `markdown-it`, so it created a situation where links to anchors worked on GitHub but did not work when converted to HTML.

I helped build `github-slugger` which `marky-markdown` uses to calculate header anchors in the same way GitHub does :)

I wonder if we could create an actual markdown-it plugin using similar code?  I do like the idea of avoiding native deps.

**Comment by ungoldman** [comment]
> I wonder if we could create an actual markdown-it plugin using similar code

I like this idea :+1:

**Comment by Flet** [comment]
https://www.npmjs.com/package/markdown-it-github-headings

Look good?

**Comment by bcomnes** [comment]
Christmas came early!  Looks sweet @Flet

**Comment by ungoldman** [comment]
This is resolved thanks to @Flet's hard work in #28 and elsewhere. Thanks! 🎉
