### ISSUE TITLE
bundle style.css with default layout

### ISSUE THREAD

**Issue by ungoldman** [hypermodules/sitedown#25]
I used this yesterday at a hack night and noticed the dev UX is a little rough around the edges, especially for someone unfamiliar with the project or new to node. I think bundling good default styles for markdown would improve the experience.

We can link directly to the dist of the latest style.css using unpkg like so:

```html
<link rel="stylesheet" href="https://unpkg.com/style.css@latest/style.css">
```

**Comment by bcomnes** [comment]
Like a default layout.html?  Agreed though

**Comment by ungoldman** [comment]
@bcomnes there's already a default layout.html, but it has no style:

https://github.com/hypermodules/sitedown/blob/master/layout.html
